// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWFfaP5daNfrhiSoiLLpnTMJeCH5580g',
    appId: '1:798450088430:web:e042c2945a6d63c1b976ff',
    messagingSenderId: '798450088430',
    projectId: 'chamasmart',
    authDomain: 'chamasmart.firebaseapp.com',
    storageBucket: 'chamasmart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKsPKCxbwUAecKg2ilQS-FT1nH9PZDj8',
    appId: '1:798450088430:android:46b1bc4d1c7b911ab976ff',
    messagingSenderId: '798450088430',
    projectId: 'chamasmart',
    storageBucket: 'chamasmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqBUyTmhVMaaFuvXpPkcXYTHi2DBNJ_U',
    appId: '1:798450088430:ios:4784f2941536bd53b976ff',
    messagingSenderId: '798450088430',
    projectId: 'chamasmart',
    storageBucket: 'chamasmart.firebasestorage.app',
    iosBundleId: 'com.example.chamasmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKqBUyTmhVMaaFuvXpPkcXYTHi2DBNJ_U',
    appId: '1:798450088430:ios:4784f2941536bd53b976ff',
    messagingSenderId: '798450088430',
    projectId: 'chamasmart',
    storageBucket: 'chamasmart.firebasestorage.app',
    iosBundleId: 'com.example.chamasmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTWFfaP5daNfrhiSoiLLpnTMJeCH5580g',
    appId: '1:798450088430:web:fa2c1a516b29f909b976ff',
    messagingSenderId: '798450088430',
    projectId: 'chamasmart',
    authDomain: 'chamasmart.firebaseapp.com',
    storageBucket: 'chamasmart.firebasestorage.app',
  );
}
